package ma.farm.model;

import java.time.LocalDate;
import java.util.Objects;

/**
 * EggProduction model - Represents daily egg production record for a specific house.
 * 
 * <p>This class tracks daily egg collection metrics including total eggs collected,
 * quality metrics (cracked vs good eggs), mortality data, and metadata about the
 * collection process.</p>
 * 
 * <p><strong>Usage Context:</strong></p>
 * <ul>
 *   <li>Dashboard - Production statistics and trends</li>
 *   <li>Eggs Bay pages - Detailed production records and analysis</li>
 * </ul>
 * 
 * <p><strong>Business Rules:</strong></p>
 * <ul>
 *   <li>Good eggs are automatically calculated as: Total Collected - Cracked Eggs</li>
 *   <li>Only applicable to egg-laying houses (H2, H3)</li>
 *   <li>One record per house per day</li>
 *   <li>Cracked eggs cannot exceed total collected eggs</li>
 * </ul>
 * 
 * @author Farm Management System
 * @version 1.0
 * @since 2024
 */
public class EggProduction {

    // ==================== Fields ====================
    
    /**
     * Unique identifier for this production record.
     * Auto-generated by database on insert.
     */
    private int id;
    
    /**
     * Foreign key reference to the House where eggs were collected.
     * Typically H2 (Egg Layer) or H3 (another egg-producing house).
     */
    private int houseId;
    
    /**
     * Date when eggs were collected.
     * Used for daily tracking and trend analysis.
     */
    private LocalDate productionDate;
    
    /**
     * Total number of eggs collected on this date.
     * Includes both good and cracked eggs.
     */
    private int eggsCollected;
    
    /**
     * Number of damaged/cracked eggs that cannot be sold.
     * Used to calculate quality metrics.
     */
    private int crackedEggs;
    
    /**
     * Number of saleable eggs (calculated field).
     * Automatically computed as: eggsCollected - crackedEggs
     */
    private int goodEggs;
    
    /**
     * Number of chicken deaths recorded on this date.
     * Used to track flock health and update house chicken count.
     */
    private int deadChickens;
    
    /**
     * Name or ID of the worker who collected the eggs.
     * Optional field for accountability and tracking.
     */
    private String collectedBy;
    
    /**
     * Additional observations or notes about the collection.
     * Examples: weather conditions, unusual findings, health concerns.
     */
    private String notes;

    // ==================== Constructors ====================
    
    /**
     * Default no-argument constructor.
     * Creates an empty EggProduction object.
     * All fields are initialized to their default values.
     */
    public EggProduction() {
    }

    /**
     * Constructor for creating a new production record with essential fields.
     * Automatically calculates good eggs from provided values.
     * 
     * <p>Use this constructor when manually entering daily production data.</p>
     * 
     * @param houseId the ID of the house where eggs were collected
     * @param productionDate the date of collection
     * @param eggsCollected total eggs collected (good + cracked)
     * @param crackedEggs number of damaged eggs
     * @param deadChickens number of deaths recorded this day
     * 
     * @throws IllegalArgumentException if crackedEggs > eggsCollected
     */
    public EggProduction(int houseId, LocalDate productionDate, int eggsCollected,
                         int crackedEggs, int deadChickens) {
        this.houseId = houseId;
        this.productionDate = productionDate;
        this.eggsCollected = eggsCollected;
        this.crackedEggs = crackedEggs;
        this.deadChickens = deadChickens;
        calculateGoodEggs();
    }

    /**
     * Full constructor with all fields.
     * Used when loading existing records from the database.
     * 
     * @param id unique identifier for this record
     * @param houseId the ID of the house where eggs were collected
     * @param productionDate the date of collection
     * @param eggsCollected total eggs collected
     * @param crackedEggs number of damaged eggs
     * @param goodEggs number of saleable eggs (pre-calculated)
     * @param deadChickens number of deaths recorded
     * @param collectedBy name/ID of the worker
     * @param notes additional observations
     */
    public EggProduction(int id, int houseId, LocalDate productionDate, int eggsCollected,
                         int crackedEggs, int goodEggs, int deadChickens,
                         String collectedBy, String notes) {
        this.id = id;
        this.houseId = houseId;
        this.productionDate = productionDate;
        this.eggsCollected = eggsCollected;
        this.crackedEggs = crackedEggs;
        this.goodEggs = goodEggs;
        this.deadChickens = deadChickens;
        this.collectedBy = collectedBy;
        this.notes = notes;
    }

    // ==================== Getters and Setters ====================
    
    /**
     * Gets the unique identifier for this production record.
     * 
     * @return the production record ID
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the unique identifier for this production record.
     * Typically set by the database after insert.
     * 
     * @param id the production record ID
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Gets the house ID where eggs were collected.
     * 
     * @return the house ID
     */
    public int getHouseId() {
        return houseId;
    }

    /**
     * Sets the house ID where eggs were collected.
     * 
     * @param houseId the house ID
     */
    public void setHouseId(int houseId) {
        this.houseId = houseId;
    }

    /**
     * Gets the date when eggs were collected.
     * 
     * @return the production date
     */
    public LocalDate getProductionDate() {
        return productionDate;
    }

    /**
     * Sets the date when eggs were collected.
     * 
     * @param productionDate the production date
     */
    public void setProductionDate(LocalDate productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * Gets the total number of eggs collected.
     * 
     * @return total eggs collected (good + cracked)
     */
    public int getEggsCollected() {
        return eggsCollected;
    }

    /**
     * Sets the total number of eggs collected.
     * Automatically recalculates good eggs when this value changes.
     * 
     * @param eggsCollected total eggs collected
     */
    public void setEggsCollected(int eggsCollected) {
        this.eggsCollected = eggsCollected;
        calculateGoodEggs();
    }

    /**
     * Gets the number of cracked/damaged eggs.
     * 
     * @return number of cracked eggs
     */
    public int getCrackedEggs() {
        return crackedEggs;
    }

    /**
     * Sets the number of cracked/damaged eggs.
     * Automatically recalculates good eggs when this value changes.
     * 
     * @param crackedEggs number of cracked eggs
     */
    public void setCrackedEggs(int crackedEggs) {
        this.crackedEggs = crackedEggs;
        calculateGoodEggs();
    }

    /**
     * Gets the number of good/saleable eggs.
     * This is a calculated field: eggsCollected - crackedEggs
     * 
     * @return number of good eggs
     */
    public int getGoodEggs() {
        return goodEggs;
    }

    /**
     * Sets the number of good eggs.
     * Generally should not be called directly as this is a calculated field.
     * Use {@link #calculateGoodEggs()} instead.
     * 
     * @param goodEggs number of good eggs
     */
    public void setGoodEggs(int goodEggs) {
        this.goodEggs = goodEggs;
    }

    /**
     * Gets the number of chicken deaths recorded on this date.
     * 
     * @return number of dead chickens
     */
    public int getDeadChickens() {
        return deadChickens;
    }

    /**
     * Sets the number of chicken deaths.
     * This value should be used to update the house's chicken count.
     * 
     * @param deadChickens number of dead chickens
     */
    public void setDeadChickens(int deadChickens) {
        this.deadChickens = deadChickens;
    }

    /**
     * Gets the name or ID of the worker who collected the eggs.
     * 
     * @return the collector's name/ID, or null if not specified
     */
    public String getCollectedBy() {
        return collectedBy;
    }

    /**
     * Sets the name or ID of the worker who collected the eggs.
     * 
     * @param collectedBy the collector's name/ID
     */
    public void setCollectedBy(String collectedBy) {
        this.collectedBy = collectedBy;
    }

    /**
     * Gets additional notes or observations about this collection.
     * 
     * @return the notes, or null if none
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets additional notes or observations.
     * Examples: "Heavy rain affected collection", "Found sick bird in H2"
     * 
     * @param notes the notes to record
     */
    public void setNotes(String notes) {
        this.notes = notes;
    }

    // ==================== Business Methods ====================

    /**
     * Calculates and updates the number of good eggs.
     * 
     * <p><strong>Formula:</strong> goodEggs = eggsCollected - crackedEggs</p>
     * 
     * <p>This method is automatically called when eggsCollected or crackedEggs
     * are modified through their setters.</p>
     * 
     * <p><strong>Example:</strong></p>
     * <pre>
     * production.setEggsCollected(1000);
     * production.setCrackedEggs(50);
     * // goodEggs is now automatically 950
     * </pre>
     */
    public void calculateGoodEggs() {
        this.goodEggs = eggsCollected - crackedEggs;
    }

    /**
     * Calculates the egg production efficiency rate.
     * 
     * <p><strong>Formula:</strong> (goodEggs / eggsCollected) × 100</p>
     * 
     * <p>This metric indicates the quality of egg production. Higher percentages
     * indicate better handling and healthier conditions.</p>
     * 
     * <p><strong>Interpretation:</strong></p>
     * <ul>
     *   <li>95-100% - Excellent quality control</li>
     *   <li>90-94% - Good quality</li>
     *   <li>85-89% - Acceptable, monitor closely</li>
     *   <li>&lt;85% - Poor quality, investigate issues</li>
     * </ul>
     * 
     * @return percentage of good eggs (0.0 to 100.0), or 0.0 if no eggs collected
     */
    public double getEfficiencyRate() {
        if (eggsCollected == 0) {
            return 0.0;
        }
        return (double) goodEggs / eggsCollected * 100;
    }

    /**
     * Calculates the percentage of cracked eggs.
     * 
     * <p><strong>Formula:</strong> (crackedEggs / eggsCollected) × 100</p>
     * 
     * <p>This metric helps identify handling or housing issues that may be
     * damaging eggs. High cracked rates may indicate:</p>
     * <ul>
     *   <li>Rough handling during collection</li>
     *   <li>Poor nesting box conditions</li>
     *   <li>Calcium deficiency in chicken feed</li>
     *   <li>Overcrowding issues</li>
     * </ul>
     * 
     * @return percentage of cracked eggs (0.0 to 100.0), or 0.0 if no eggs collected
     */
    public double getCrackedRate() {
        if (eggsCollected == 0) {
            return 0.0;
        }
        return (double) crackedEggs / eggsCollected * 100;
    }

    /**
     * Validates the production data for logical consistency.
     * 
     * <p><strong>Validation Rules:</strong></p>
     * <ul>
     *   <li>eggsCollected must be non-negative</li>
     *   <li>crackedEggs must be non-negative</li>
     *   <li>crackedEggs cannot exceed eggsCollected</li>
     *   <li>deadChickens must be non-negative</li>
     * </ul>
     * 
     * <p>Use this method before saving data to ensure integrity.</p>
     * 
     * @return true if all validation rules pass, false otherwise
     */
    public boolean isValid() {
        return eggsCollected >= 0 
            && crackedEggs >= 0 
            && crackedEggs <= eggsCollected
            && deadChickens >= 0;
    }

    // ==================== Object Methods ====================

    /**
     * Compares this production record to another object for equality.
     * Two production records are considered equal if they have the same ID.
     * 
     * @param o the object to compare with
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        EggProduction that = (EggProduction) o;
        return id == that.id;
    }

    /**
     * Generates a hash code for this production record.
     * Based solely on the ID field.
     * 
     * @return the hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    /**
     * Returns a string representation of this production record.
     * Includes all fields for debugging and logging purposes.
     * 
     * @return a detailed string representation
     */
    @Override
    public String toString() {
        return "EggProduction{" +
                "id=" + id +
                ", houseId=" + houseId +
                ", productionDate=" + productionDate +
                ", eggsCollected=" + eggsCollected +
                ", crackedEggs=" + crackedEggs +
                ", goodEggs=" + goodEggs +
                ", deadChickens=" + deadChickens +
                ", collectedBy='" + collectedBy + '\'' +
                ", notes='" + notes + '\'' +
                '}';
    }
}